[openai]
endpoint = "http://kuro.local:8081/v1"

[system_prompt]
text = "日本語で応答せよ。返答にサマリー的文言不要であるので、内容だけ提示せよ。説明はできるだけ箇条書きとせよ。可能な限り詳細に、省略するな。"

[prompts]
choices = [
    "画像を簡素に説明せよ",
    "画像をできるだけ詳細に説明せよ",
    "レイアウトやボタン配置、ＵＩエレメントなどを優先して、できるだ詳細に説明せよ",
    "テキストを正確に文字化せよ",
    "以下のセクションでできるだけ詳細に説明せよ。# 概要 / # レイアウトやボタン配置、ＵＩエレメント / # 正確なテキスト文字"
]
